services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=find_a_friend
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker